### ISSUE TITLE
Erroe on line 36:4:TypeError: undefined is not an objec (evaluation 'l.layoutHorizontally')

### ISSUE THREAD

**Issue by DarinXie** [zqrren/GitHub-Contributions-Script#1]

**Comment by zqrren** [comment]
```javascript
let l1 = w.addStack()
let l2 = w.addStack()
let l3 = w.addStack()
let l4 = w.addStack()
let l5 = w.addStack()
let l6 = w.addStack()
let l7 = w.addStack()
```
请注意这部分是否完整，若出现下面情况则有可能产生此错误
```javascript
let l1 = w.addStack()
let l2 = w.addStack()
let l3 = w.addStack()
let l4 = w.addStack()
let l5 = w.addStack()
let l6 = w.addStack()
let l7
```

**Comment by DarinXie** [comment]
这里也有一个错误:
Error on line 25:20: TypeError: w.addStack is not a function. (In 'w.addStack()','w.addStack' is undefined)

**Comment by DarinXie** [comment]
> 这里也有一个错误:
> Error on line 25:20: TypeError: w.addStack is not a function. (In 'w.addStack()','w.addStack' is undefined)

在我删掉括号后，这个错误就没有了，显示的是上一次说的那个错误。已经改了用户名。

**Comment by zqrren** [comment]
> 这里也有一个错误:
> Error on line 25:20: TypeError: w.addStack is not a function. (In 'w.addStack()','w.addStack' is undefined)

`addStack()`为内测中的 [Scriptable 1.5.1](https://testflight.apple.com/join/uN1vTqxk) 的新功能，请检查当前版本号
